"""Agent tool definitions for WealthSandBox.

These schemas follow the OpenAI function-calling format so that LLM agents
can reason in natural language and then call tools to produce the
environment's ``Action``.

All tool descriptions are generated by ``build_tools()`` so dollar amounts,
durations, and occupation data always match the active ``EnvConfig`` and
``CareerSystem`` — no magic numbers.
"""

from dataclasses import dataclass
from typing import Any, Dict, List, Optional


# ---------------------------------------------------------------------------
# Tool-name constants
# ---------------------------------------------------------------------------
SWITCH_OCCUPATION = "switch_occupation"
UPSKILL = "upskill"
INTENSIVE_WORK = "intensive_work"
QUIT_JOB = "quit_job"

ALL_TOOL_NAMES = {SWITCH_OCCUPATION, UPSKILL, INTENSIVE_WORK, QUIT_JOB}


# ---------------------------------------------------------------------------
# Dynamic tool builder
# ---------------------------------------------------------------------------

def build_tools(
    living_expense: float = 2_000.0,
    upskill_cost: float = 5_000.0,
    upskill_months: int = 6,
    upskill_skill_boost: int = 1,
    max_general_skill: int = 10,
    switch_base_cost: float = 2_000.0,
    energy_threshold: float = 0.4,
    intensive_work_months: int = 3,
    max_occ_skill: int = 10,
    occ_skill_passive_months: int = 12,
    occupations: Optional[Dict[str, Any]] = None,
) -> List[Dict[str, Any]]:
    """Build the tool definitions with dynamic costs and occupation data."""

    # --- quit_job ---
    quit_job_desc = (
        f"Voluntarily quit your current job.  You become unemployed "
        f"immediately — your occupation is cleared and your monthly "
        f"income drops to $0.  Living expenses (${living_expense:,.0f}/month) "
        f"still apply, so make sure you have enough savings.  You can "
        f"switch to a new occupation later.  Has no effect if you "
        f"are already unemployed."
    )

    # --- switch_occupation ---
    occ_list_parts: List[str] = []
    if occupations:
        for occ_id, detail in sorted(occupations.items()):
            total = switch_base_cost + detail.get("entry_cost", 0)
            train = detail.get("training_months", 0)
            req = detail.get("min_general_skill", 1)
            min_h = detail.get("min_health", 0.0)
            tiers = detail.get("tiers", [])
            top_tier = tiers[-1]["salary_multiplier"] if tiers else 1.0
            occ_list_parts.append(
                f"{occ_id} (gen_skill≥{req}, health≥{min_h:.1f}, "
                f"${total:,.0f}+{train}mo, ceiling ×{top_tier:.1f})"
            )
    occ_list_str = ", ".join(occ_list_parts) if occ_list_parts else (
        "see the observation for available occupations"
    )

    switch_occupation_desc = (
        f"Switch to a different occupation.  Each occupation has a minimum "
        f"general skill requirement, a minimum health requirement, an entry "
        f"cost + training period, and a tier ladder (salary ceiling).  "
        f"Your **general skill** carries over (partial for cross-industry "
        f"switches), but your **occupation-specific skill** resets to the "
        f"starting tier.  Health declines with age — physically demanding "
        f"jobs will become inaccessible AND you will be forced to resign if "
        f"your health drops below the occupation's threshold while employed.  "
        f"Base switch cost is ${switch_base_cost:,.0f} + entry cost.  "
        f"Available occupations: {occ_list_str}."
    )

    # --- upskill (general skill) ---
    upskill_desc = (
        f"Improve your **general skill** by {upskill_skill_boost} "
        f"(max {max_general_skill}).  General skill determines which "
        f"occupations you can enter and also boosts your salary in ANY "
        f"occupation via the skill-sensitivity formula.  "
        f"Costs ${upskill_cost:,.0f} + {energy_threshold:.0%} energy.  "
        f"Takes {upskill_months} months (you continue working normally).  "
        f"Cannot start a new upskill while one is already in progress."
    )

    # --- intensive_work (occupation skill) ---
    intensive_work_desc = (
        f"Invest extra effort to improve your **occupation-specific skill** "
        f"in your current job by +1 (max {max_occ_skill}).  Occupation skill "
        f"determines your tier (Junior → Mid-level → Senior → ...) and "
        f"therefore your salary multiplier.  "
        f"Costs {energy_threshold:.0%}+ energy — NO cash cost.  "
        f"Takes {intensive_work_months} months (you continue working normally).  "
        f"Note: occupation skill grows passively by +1 every "
        f"{occ_skill_passive_months} months of tenure — intensive_work "
        f"accelerates this.  Occupation skill is NOT carried when you switch "
        f"occupations.  Only available when employed."
    )

    return [
        {
            "type": "function",
            "function": {
                "name": "quit_job",
                "description": quit_job_desc,
                "parameters": {"type": "object", "properties": {}},
            },
        },
        {
            "type": "function",
            "function": {
                "name": "switch_occupation",
                "description": switch_occupation_desc,
                "parameters": {
                    "type": "object",
                    "properties": {
                        "occupation_id": {
                            "type": "string",
                            "description": (
                                "The target occupation id, e.g. 'software_engineer', "
                                "'nurse', 'civil_servant'."
                            ),
                        }
                    },
                    "required": ["occupation_id"],
                },
            },
        },
        {
            "type": "function",
            "function": {
                "name": "upskill",
                "description": upskill_desc,
                "parameters": {"type": "object", "properties": {}},
            },
        },
        {
            "type": "function",
            "function": {
                "name": "intensive_work",
                "description": intensive_work_desc,
                "parameters": {"type": "object", "properties": {}},
            },
        },
    ]


# ---------------------------------------------------------------------------
# Default TOOLS (backward compatibility)
# ---------------------------------------------------------------------------
TOOLS: List[Dict[str, Any]] = build_tools()


# ---------------------------------------------------------------------------
# Data structures
# ---------------------------------------------------------------------------

@dataclass
class ToolCall:
    """A single tool call produced by the LLM."""

    tool_name: str
    parameters: Dict[str, Any]


@dataclass
class Decision:
    """The complete output of the LLM agent for one turn.

    Attributes:
        reasoning: Natural-language explanation of the decision.
        tool_calls: List of tools the agent chose to invoke.
    """

    reasoning: str
    tool_calls: List[ToolCall]
