"""Agent tool definitions for WealthSandBox.

These schemas follow the OpenAI function-calling format so that LLM agents
can reason in natural language and then call tools to produce the
environment's ``Action``.

All tool descriptions are generated by ``build_tools()`` so dollar amounts,
durations, and occupation data always match the active ``EnvConfig`` and
``CareerSystem`` — no magic numbers.
"""

from dataclasses import dataclass
from typing import Any, Dict, List, Optional


# ---------------------------------------------------------------------------
# Tool-name constants
# ---------------------------------------------------------------------------
SWITCH_OCCUPATION = "switch_occupation"
UPSKILL = "upskill"
INTENSIVE_WORK = "intensive_work"
QUIT_JOB = "quit_job"
DEPOSIT = "deposit"
WITHDRAW = "withdraw"
BORROW = "borrow"
REPAY = "repay"
BUY_STOCK = "buy_stock"
SELL_STOCK = "sell_stock"
REST = "rest"
MEDICAL_CARE = "medical_care"

ALL_TOOL_NAMES = {SWITCH_OCCUPATION, UPSKILL, INTENSIVE_WORK, QUIT_JOB, DEPOSIT, WITHDRAW, BORROW, REPAY, BUY_STOCK, SELL_STOCK, REST, MEDICAL_CARE}


# ---------------------------------------------------------------------------
# Dynamic tool builder
# ---------------------------------------------------------------------------

def build_tools(
    living_expense: float = 2_000.0,
    upskill_cost: float = 5_000.0,
    upskill_months: int = 6,
    upskill_skill_boost: int = 1,
    max_general_skill: int = 10,
    switch_base_cost: float = 2_000.0,
    energy_threshold: float = 0.30,
    upskill_energy_footprint: float = 0.15,
    intensive_work_energy_footprint: float = 0.20,
    intensive_work_months: int = 3,
    max_occ_skill: int = 10,
    occ_skill_passive_months: int = 12,
    occupations: Optional[Dict[str, Any]] = None,
    min_cash_buffer: float = 2_000.0,
    forced_sale_discount: float = 0.10,
    rest_health_gain: float = 0.02,
    rest_income_penalty: float = 0.20,
    medical_care_cost: float = 3_000.0,
    medical_care_health_gain: float = 0.05,
    medical_care_max_per_year: int = 2,
) -> List[Dict[str, Any]]:
    """Build the tool definitions with dynamic costs and occupation data."""

    # --- quit_job ---
    quit_job_desc = (
        f"Voluntarily quit your current job.  You become unemployed "
        f"immediately — your occupation is cleared and your monthly "
        f"income drops to $0.  Living expenses (${living_expense:,.0f}/month) "
        f"still apply, so make sure you have enough savings.  You can "
        f"switch to a new occupation later.  Has no effect if you "
        f"are already unemployed."
    )

    # --- switch_occupation ---
    occ_list_parts: List[str] = []
    if occupations:
        for occ_id, detail in sorted(occupations.items()):
            total = switch_base_cost + detail.get("entry_cost", 0)
            train = detail.get("training_months", 0)
            req = detail.get("min_general_skill", 1)
            min_h = detail.get("min_health", 0.0)
            tiers = detail.get("tiers", [])
            top_tier = tiers[-1]["salary_multiplier"] if tiers else 1.0
            occ_list_parts.append(
                f"{occ_id} (gen_skill≥{req}, health≥{min_h:.1f}, "
                f"${total:,.0f}+{train}mo, ceiling ×{top_tier:.1f})"
            )
    occ_list_str = ", ".join(occ_list_parts) if occ_list_parts else (
        "see the observation for available occupations"
    )

    switch_occupation_desc = (
        f"Switch to a different occupation.  Each occupation has a minimum "
        f"general skill requirement, a minimum health requirement, an entry "
        f"cost + training period, and a tier ladder (salary ceiling).  "
        f"Your **general skill** carries over (partial for cross-industry "
        f"switches), but your **occupation-specific skill** resets to the "
        f"starting tier.  Health declines with age — physically demanding "
        f"jobs will become inaccessible AND you will be forced to resign if "
        f"your health drops below the occupation's threshold while employed.  "
        f"Base switch cost is ${switch_base_cost:,.0f} + entry cost.  "
        f"Available occupations: {occ_list_str}."
    )

    # --- upskill (general skill) ---
    upskill_desc = (
        f"Improve your **general skill** by {upskill_skill_boost} "
        f"(max {max_general_skill}).  General skill determines which "
        f"occupations you can enter and also boosts your salary in ANY "
        f"occupation via the skill-sensitivity formula.  "
        f"Costs ${upskill_cost:,.0f} and occupies {upskill_energy_footprint:.0%} "
        f"of your energy for {upskill_months} months (you continue working "
        f"normally).  "
        f"Cannot start a new upskill while one is already in progress."
    )

    # --- intensive_work (occupation skill) ---
    intensive_work_desc = (
        f"Invest extra effort to improve your **occupation-specific skill** "
        f"in your current job by +1 (max {max_occ_skill}).  Occupation skill "
        f"determines your tier (Junior → Mid-level → Senior → ...) and "
        f"therefore your salary multiplier.  "
        f"Occupies {intensive_work_energy_footprint:.0%} of your energy — NO cash cost.  "
        f"Takes {intensive_work_months} months (you continue working normally).  "
        f"Note: occupation skill grows passively by +1 every "
        f"{occ_skill_passive_months} months of tenure — intensive_work "
        f"accelerates this.  Occupation skill is NOT carried when you switch "
        f"occupations.  Only available when employed."
    )

    # --- rest (recover health + energy, at the cost of income) ---
    rest_desc = (
        f"Take a month of light duty to recover.  Restores "
        f"{rest_health_gain:.2f} health and releases the non-work energy "
        f"occupancy (training/upskill/intensive work) this month, but you "
        f"earn only {1 - rest_income_penalty:.0%} of your normal income this "
        f"month.  It cannot reduce your job's own energy occupancy.  Useful "
        f"when health is dropping toward your occupation's minimum, or your "
        f"free energy is too low to upskill / work intensively."
    )

    # --- medical_care (pay cash to recover health) ---
    medical_care_desc = (
        f"Pay ${medical_care_cost:,.0f} for medical treatment, restoring "
        f"{medical_care_health_gain:.2f} health immediately (capped at the "
        f"maximum).  Limited to {medical_care_max_per_year} uses per year."
    )

    return [
        {
            "type": "function",
            "function": {
                "name": "quit_job",
                "description": quit_job_desc,
                "parameters": {"type": "object", "properties": {}},
            },
        },
        {
            "type": "function",
            "function": {
                "name": "deposit",
                "description": (
                    f"Deposit cash into your bank savings account.  Earns "
                    f"monthly interest at the federal funds rate / 12.  "
                    f"Must keep ≥${living_expense:,.0f} cash after deposit.  "
                    f"Example: deposit(amount=3000)."
                ),
                "parameters": {
                    "type": "object",
                    "properties": {
                        "amount": {"type": "number", "description": "Amount to deposit."},
                    },
                    "required": ["amount"],
                },
            },
        },
        {
            "type": "function",
            "function": {
                "name": "withdraw",
                "description": (
                    f"Withdraw from your bank savings account.  "
                    f"Example: withdraw(amount=2000)."
                ),
                "parameters": {
                    "type": "object",
                    "properties": {
                        "amount": {"type": "number", "description": "Amount to withdraw."},
                    },
                    "required": ["amount"],
                },
            },
        },
        {
            "type": "function",
            "function": {
                "name": "borrow",
                "description": (
                    f"Take a bank loan.  Loan limit = 12 × income if employed, "
                    f"$8,000 if unemployed.  Interest charged "
                    f"monthly at (federal funds rate + 2%) / 12.  Example: "
                    f"borrow(amount=5000)."
                ),
                "parameters": {
                    "type": "object",
                    "properties": {
                        "amount": {"type": "number", "description": "Amount to borrow."},
                    },
                    "required": ["amount"],
                },
            },
        },
        {
            "type": "function",
            "function": {
                "name": "repay",
                "description": (
                    f"Repay part or all of your bank loan.  "
                    f"Example: repay(amount=2000).  Repaying the full "
                    f"balance stops further interest charges."
                ),
                "parameters": {
                    "type": "object",
                    "properties": {
                        "amount": {"type": "number", "description": "Amount to repay."},
                    },
                    "required": ["amount"],
                },
            },
        },
        {
            "type": "function",
            "function": {
                "name": "switch_occupation",
                "description": switch_occupation_desc,
                "parameters": {
                    "type": "object",
                    "properties": {
                        "occupation_id": {
                            "type": "string",
                            "description": (
                                "The target occupation id, e.g. 'software_engineer', "
                                "'nurse', 'civil_servant'."
                            ),
                        }
                    },
                    "required": ["occupation_id"],
                },
            },
        },
        {
            "type": "function",
            "function": {
                "name": "upskill",
                "description": upskill_desc,
                "parameters": {"type": "object", "properties": {}},
            },
        },
        {
            "type": "function",
            "function": {
                "name": "intensive_work",
                "description": intensive_work_desc,
                "parameters": {"type": "object", "properties": {}},
            },
        },
        {
            "type": "function",
            "function": {
                "name": "rest",
                "description": rest_desc,
                "parameters": {"type": "object", "properties": {}},
            },
        },
        {
            "type": "function",
            "function": {
                "name": "medical_care",
                "description": medical_care_desc,
                "parameters": {"type": "object", "properties": {}},
            },
        },
        {
            "type": "function",
            "function": {
                "name": "buy_stock",
                "description": (
                    f"Move cash into a stock index fund.  Purchases do NOT earn "
                    f"this month's market return — your money only starts "
                    f"growing next month.  Stock value fluctuates monthly with "
                    f"the market.  Must keep ≥${min_cash_buffer:,.0f} cash "
                    f"for living expenses.  Example: buy_stock(amount=5000)."
                ),
                "parameters": {
                    "type": "object",
                    "properties": {
                        "amount": {"type": "number", "description": "Amount to invest in stocks."},
                    },
                    "required": ["amount"],
                },
            },
        },
        {
            "type": "function",
            "function": {
                "name": "sell_stock",
                "description": (
                    f"Sell stocks.  Proceeds settle NEXT month and cannot cover "
                    f"this month's expenses.  Example: sell_stock(amount=3000)."
                ),
                "parameters": {
                    "type": "object",
                    "properties": {
                        "amount": {"type": "number", "description": "Amount of stocks to sell."},
                    },
                    "required": ["amount"],
                },
            },
        },
    ]


# ---------------------------------------------------------------------------
# Default TOOLS (backward compatibility)
# ---------------------------------------------------------------------------
TOOLS: List[Dict[str, Any]] = build_tools()


# ---------------------------------------------------------------------------
# Data structures
# ---------------------------------------------------------------------------

@dataclass
class ToolCall:
    """A single tool call produced by the LLM."""

    tool_name: str
    parameters: Dict[str, Any]


@dataclass
class Decision:
    """The complete output of the LLM agent for one turn.

    Attributes:
        reasoning: Natural-language explanation of the decision.
        tool_calls: List of tools the agent chose to invoke.
    """

    reasoning: str
    tool_calls: List[ToolCall]
